version: '3'

services:
  spring-starter-kit:
    image: ${DEV_SPRING_IMAGE}
    container_name: dev-spring-starter-kit-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: ${DEV_DB_USERNAME}
      DB_USERNAME: ${DEV_DB_USERNAME}
      DB_PASSWORD: ${DEV_DB_PASSWORD}
      REDIS_HOST: ${DEV_REDIS_HOST}
      REDIS_PORT: ${DEV_REDIS_PORT}
    depends_on:
      - mariadb
      - redis
