version: '3'

services:
  spring-starter-kit:
    image: ${DOCKERHUB_USERNAME}/spring-starter-kit:dev
    container_name: dev-spring-starter-kit-container
    ports:
      - "${DEV_SPRING_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://dev-mysql-container:3306/${DEV_MYSQL_DATABASE}
      DB_USERNAME: ${DEV_MYSQL_USERNAME}
      DB_PASSWORD: ${DEV_MYSQL_PASSWORD}
      REDIS_HOST: dev-redis-container
      REDIS_PORT: ${DEV_REDIS_PORT}
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:latest
    container_name: dev-mysql-container
    ports:
      - "${DEV_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DEV_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DEV_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${DEV_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DEV_MYSQL_PASSWORD}
    volumes:
      - dev_mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: dev-redis-container
    ports:
      - "${DEV_REDIS_PORT}:6379"
    volumes:
      - dev_redis_data:/data

volumes:
  dev_mysql_data:
  dev_redis_data:
