version: '3'

services:
  spring-starter-kit:
    image: ${DOCKERHUB_USERNAME}/spring-starter-kit:prod
    container_name: prod-spring-starter-kit-container
    ports:
      - "${PROD_SPRING_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mariadb://prod-mariadb-container:3306/${PROD_MYSQL_DATABASE}
      DB_USERNAME: ${PROD_MYSQL_USERNAME}
      DB_PASSWORD: ${PROD_MYSQL_PASSWORD}
      REDIS_HOST: prod-redis-container
      REDIS_PORT: ${PROD_REDIS_PORT}
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: prod-mariadb-container
    ports:
      - "${PROD_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${PROD_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${PROD_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${PROD_MYSQL_PASSWORD}
    volumes:
      - prod_mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: prod-redis-container
    ports:
      - "${PROD_REDIS_PORT}:6379"
    volumes:
      - prod_redis_data:/data

volumes:
  prod_mariadb_data:
  prod_redis_data:
