version: '3'

services:
  spring-starter-kit:
    image: ${PROD_SPRING_IMAGE}
    container_name: prod-spring-starter-kit-container
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${PROD_DB_USERNAME}
      DB_USERNAME: ${PROD_DB_USERNAME}
      DB_PASSWORD: ${PROD_DB_PASSWORD}
      REDIS_HOST: ${PROD_REDIS_HOST}
      REDIS_PORT: ${PROD_REDIS_PORT}
    depends_on:
      - mariadb
      - redis
