version: '3'

services:
  spring-starter-kit:
    image: ${DOCKERHUB_USERNAME}/spring-starter-kit:dev
    container_name: dev-spring-starter-kit-container
    ports:
      - "${DEV_SPRING_PORT}:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mariadb://dev-mariadb-container:3306/${DEV_MYSQL_DATABASE}
      DB_USERNAME: ${DEV_DB_USERNAME}
      DB_PASSWORD: ${DEV_DB_PASSWORD}
      REDIS_HOST: dev-redis-container
      REDIS_PORT: ${DEV_REDIS_PORT}
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: dev-mariadb-container
    ports:
      - "${DEV_DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DB_PASSWORD}
      MYSQL_DATABASE: ${DEV_MYSQL_DATABASE}
      MYSQL_USER: ${DEV_DB_USERNAME}
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: dev-redis-container
    ports:
      - "${DEV_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
