spring:
  config:
    activate:
      on-profile: local
  sql:
    init:
      mode: always
      data-locations: classpath:db/migration/data.sql
      schema-locations: classpath:db/migration/schema.sql
  datasource:
    url: jdbc:mysql://localhost:3306/spring-starter-kit
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none # 초기에 많이 변경되는 경우엔 update도 많이 사용함.
#    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379