spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: never
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
