spring:
  config:
    activate:
      on-profile: prod
  sql:
    init:
      mode: never
  datasource:
    url: ${PROD_MYSQL_DATABASE_URL}
    username: ${PROD_MYSQL_USERNAME}
    password: ${PROD_MYSQL_PASSWORD}
  redis:
    host: ${PROD_REDIS_HOST}
    port: ${PROD_REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: none