spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  #    defer-datasource-initialization: never
  redis:
    host: ${DEV_REDIS_HOST}
    port: ${DEV_REDIS_PORT}
