name: CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Development Server
        if: github.ref_name == 'dev'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.DEV_SERVER_HOST }}
          username: ${{ secrets.DEV_SERVER_USER }}
          key: ${{ secrets.DEV_SERVER_SSH_KEY }}
          port: ${{ secrets.DEV_SERVER_SSH_PORT }}
          envs:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
            SPRING_IMAGE_TAG: 'dev'
          script: |
            cd /path/to/your/docker-compose/files
            export DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
            export SPRING_IMAGE_TAG=${SPRING_IMAGE_TAG}
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml pull spring-starter-kit
            docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d

      - name: Deploy to Production Server
        if: github.ref_name == 'main'
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USER }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          port: ${{ secrets.PROD_SERVER_SSH_PORT }}
          envs:
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
            SPRING_IMAGE_TAG: 'prod'
          script: |
            cd /path/to/your/docker-compose/files
            export DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
            export SPRING_IMAGE_TAG=${SPRING_IMAGE_TAG}
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull spring-starter-kit
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
